### ISSUE TITLE
Add support for Codec's AMK 1.1.0 Beta (parser version 3)

### ISSUE THREAD

**Issue by KungFuFurby** [KungFuFurby/AddMusicKFF#216]
This is a special instance of me being interested in adding support for a version that never got to a finalized version. This is because of its existence in the first place, as well as a public build with SPC700-side source code extant. I will have to manually convert the VCMDs that it uses (and implement a few new ones) in order to account for this situation, and I probably won't do all of the flags right off the bat that this thing has due to me going off-track due to an initial lack of interest.

In order for me to successfully pull this off, I need the C++-side code (which is currently not included in the latest known build) in order to properly replicate the behavior required for AMK parser version 3, which is what this uses. I will be using parser version 4 for my own fork and modifications. I have since acquired the C++-side code from the original developer, so that means I can now go ahead and go for it.

There is at least one conflict (which means this will be parser version 3 only):
- `%` is used for percussion. #223 reserves the same character for binary numbers. This is a conflict that has to be resolved for whatever parser version I implement that in.

The music parser additions (and modifications) are...
- [ ] New character `:` - breaks out of an $E9 loop (requires #89)
- [ ] New character `%` - triggers percussion ID
- [ ] `v` is enhanced to support slides
- [ ] `t` is enhanced to support slides
- [ ] `w` is enhanced to support slides
- [ ] `(!!)` resets remote code. (#232 contains a replacement for this through remote code event IDs)
  - `(!!0)` resets both key on and non-key on remote commands
  - `(!!-1)` resets "on key on" remote commands
  - Any other value resets non-"on key on" remote commands
- [ ] `#allsamplesimportant` is new. Optimizations are forced off for everything. For my case, this is only relevant for sample groups due to #121 and #123 being resolved.
- [ ] `#notranspose` is new. See #253: I have a similar plan.
- [ ] `#percussion` is new and defines custom percussion. This... is problematic because of #130 , which has different intentions. Also, this overwrites the global percussion table. Technically I can replicate that with a VCMD not unlike what was used in AddmusicO, but again, this is conflicting...
- [ ] `#efficient` decreases the accuracy of the pitch in exchange for speed. Requires a SPC-side modification... and since I use phrases, either a new VCMD (a `$F4` command in this case) or a hot patch bit.
  - This affects the SetPitch code, specifically its frequency of updating pitches. The amount of times this skips per call (unless forced) is user-configurable.
- [ ] `#semiefficient` decreases the accuracy of the vibrato in exchange for speed. Requires a SPC-side modification... and since I use phrases, either a new VCMD (a `$F4` command in this case) or a hot patch bit.
  - This affects the frequency that the pitch bends are processed outside of a music tempo tick (that is, on every timer 0 tick). Specifically, they are now processed every four timer 0 ticks. This is an easier hot patch setup than the `#efficient` one, at least in theory.

Translations...
- [ ] `$F4 $0A` -> `$FD`
- [ ] `$F4 $0B` -> `$FE`
- [ ] `$F4 $0C` -> `$FC $00 ?? ?? ??`
- [ ] `$F4 $0D` -> `$FC $07 ?? ?? ??` (requires #232 which contains this event)
- [ ] `$F4 $0E` -> `$FC $08 ?? ?? ??` (requires #232 which contains this event)
- [ ] `$F4 $0F` -> TODO (I'm keeping phrases, so I will instead use a VCMD to add to the end of the phrase or song)
- [ ] `$F4 $10` -> `$F4 $21` (requires #89)

Unimplemented at the time of the release of the last beta:
- `#instperc`
