### ISSUE TITLE
Create new parser version 4

### ISSUE THREAD

**Issue by KungFuFurby** [KungFuFurby/AddMusicKFF#278]
Citing https://smwc.me/1599381 and the few replies I have received, I will go through with parser version 4.

Parser version 4 will do the following:
- [x] Incorporate what was implemented in #1

All older versions will output warnings for running into the following...
- [x] Using uppercase letters as note data (#246)
- [x] Using `o` while specifying a note on a `$DD` hex command (#27)
- [x] Using fractional note lengths (#304, whose fix debuts for parser version 4 first)

I will also support some of the parser version 3 features as indicated in #216. Anything related to new hex commands will not be covered, and conversions in particular are parser version 3 only.
The following also needs to be done...
- [x] `v`, `t` and `w` need to have their durations divided by the tempo ratio. I cannot correct this for parser version 3 because it was like that as of the last public release in May 2017, but I *can* do this for parser version 4. I later discovered that this would not have worked because of #304, therefore I had to implement a fix through that.
